/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_dataworker_free(a: number): void;
export function __wbg_chunk_free(a: number): void;
export function chunk_new(a: number, b: number, c: number, d: number, e: number): number;
export function chunk_length(a: number): number;
export function chunk_count(a: number): number;
export function chunk_data(a: number): number;
export function chunk_min(a: number): number;
export function chunk_max(a: number): number;
export function chunk_sum(a: number): number;
export function chunk_avg(a: number): number;
export function chunk_keys(a: number): number;
export function chunk_transform(a: number, b: number): number;
export function chunk_sort(a: number, b: number, c: number, d: number): void;
export function chunk_expose_key_int(a: number, b: number, c: number): number;
export function chunk_expose_key_float(a: number, b: number, c: number): number;
export function chunk_expose_key_string(a: number, b: number, c: number): number;
export function chunk_to_object(a: number): number;
export function chunk_select(a: number, b: number): void;
export function dataworker_getData(a: number, b: number, c: number): number;
export function dataworker_append(a: number, b: number, c: number, d: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h40c816f015435947(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h84d25aa449a68259(a: number, b: number, c: number, d: number): void;
